[phases.setup]
nixPkgs = [
  "gcc",
  "python39",
  "postgresql_16",
]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[start]
cmd = "python3 manage.py migrate && gunicorn myproject.wsgi:application"
