[phases.setup]
nixPkgs = [
  "gcc",
  "python39Full",            # Includes pip and python3 binary
  "postgresql_16"
]

[phases.install]
cmds = [
  "echo Python path: $(which python3)",
  "python3 --version",
  "python3 -m pip --version",
  "python3 -m pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python3 manage.py migrate && gunicorn myproject.wsgi:application"
