[phases.setup]
nixPkgs = [
  # This brings in python with pip and setuptools
  "python39Packages.pip",
  "python39Packages.setuptools",
  "gcc",
  "postgresql_16"
]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python3 manage.py migrate && gunicorn myproject.wsgi:application"
